### ISSUE TITLE
.flatten() incorrectly typed 

### ISSUE THREAD

**Issue by wojciechprzerwa** [dphilipson/transducist#17]
TansformationChain<SomeType>.flatten: void

This expression is not callable. Type 'void' has no call signatures.

.flatten appears to be wrongly typed

Code example:

chainFrom(someData)
  .filter(({ prop }) => prop)
  .map(({ prop }) => prop * 2)
  .flatten() // Error
  .toArray()

**Comment by dphilipson** [comment]
Hi there!

`.flatten` has type `T extends Iterable<infer U> ? () => TransformChain<U> : void`, meaning that it is defined if the values in the chain are currently iterables but undefined otherwise ([defined here](https://github.com/dphilipson/transducist/blob/master/src/chain.ts#L57)). If you're seeing it as type `void`, it may mean that your values are not iterables.

For example, the following works for me:
```ts
chainFrom([
  [1, 2],
  [3, 4],
])
  .flatten()
  .toArray();
// -> [1, 2, 3, 4]
```
while the following is correctly classified as an error:
```ts
chainFrom([1, 2, 3, 4]).flatten().toArray();
//                      ^^^^^^^
// This expression is not callable.
```
Does that explain the error you're seeing? If not, can you add the type of the input to your example so I can investigate?

Thanks very much!
